export const MISSING_SHEET_DEFINITION = 'MISSING_SHEET_DEFINITION';
export const MISSING_MATCHUP_DETAILS = 'MISSING_MATCHUP_DETAILS';
export const INVALID_MATCHUPS_TOTAL = 'INVALID_MATCHUPS_TOTAL';
export const NO_POSITION_ROWS_FOUND = 'NO_POSITION_ROWS_FOUND';
export const NO_PARTICIPANTS_FOUND = 'NO_PARTICIPANTS_FOUND';
export const UNKNOWN_WORKBOOK_TYPE = 'UNKNOWN_WORKBOOK_TYPE';
export const UNKNOWN_SHEET_TYPE = 'UNKNOWN_SHEET_TYPE';
export const MISSING_ATTRIBUTES = 'MISSING_ATTRIBUTES';
export const MISSING_ID_COLUMN = 'MISSING_ID_COLUMN';
export const MISSING_WORKBOOK = 'MISSING_WORKBOOK';
export const MULTIPLE_MATCHES = 'MULTIPLE_MATCHES';
export const NO_RESULTS_FOUND = 'NO_RESULTS_FOUND';
export const MISSING_MATCHUP = 'MISSING_MATCHUP';
export const INVALID_VALUES = 'INVALID_VALUES';
export const MISSING_VALUES = 'MISSING_VALUES';
export const VALUE_MISMATCH = 'VALUE_MISMATCH';
export const MISSING_NAMES = 'MISSING_NAMES';

export const errorConditionConstants = {
  MISSING_SHEET_DEFINITION,
  MISSING_MATCHUP_DETAILS,
  INVALID_MATCHUPS_TOTAL,
  NO_POSITION_ROWS_FOUND,
  NO_PARTICIPANTS_FOUND,
  UNKNOWN_WORKBOOK_TYPE,
  MISSING_ATTRIBUTES,
  UNKNOWN_SHEET_TYPE,
  MISSING_ID_COLUMN,
  MISSING_WORKBOOK,
  MULTIPLE_MATCHES,
  NO_RESULTS_FOUND,
  MISSING_MATCHUP,
  INVALID_VALUES,
  MISSING_VALUES,
  VALUE_MISMATCH,
  MISSING_NAMES
};
