export const MISSING_SHEET_DEFINITION = 'MISSING_SHEET_DEFINITION';
export const UNKNOWN_SHEET_TYPE = 'UNKNOWN_SHEET_TYPE';
export const MISSING_WORKBOOK = 'MISSING_WORKBOOK';

export const errorConditionConstants = {
  MISSING_SHEET_DEFINITION,
  UNKNOWN_SHEET_TYPE,
  MISSING_WORKBOOK
};
