export const MISSING_SHEET_DEFINITION = 'MISSING_SHEET_DEFINITION';
export const UNKNOWN_WORKBOOK_TYPE = 'UNKNOWN_WORKBOOK_TYPE';
export const UNKNOWN_SHEET_TYPE = 'UNKNOWN_SHEET_TYPE';
export const MISSING_ATTRIBUTES = 'MISSING_ATTRIBUTES';
export const MISSING_WORKBOOK = 'MISSING_WORKBOOK';
export const MISSING_MATCHUP = 'MISSING_MATCHUP';
export const INVALID_VALUES = 'INVALID_VALUES';
export const MISSING_VALUES = 'MISSING_VALUES';

export const errorConditionConstants = {
  MISSING_SHEET_DEFINITION,
  UNKNOWN_WORKBOOK_TYPE,
  MISSING_ATTRIBUTES,
  UNKNOWN_SHEET_TYPE,
  MISSING_WORKBOOK,
  MISSING_MATCHUP,
  INVALID_VALUES,
  MISSING_VALUES
};
