export const roundNames = [
  { text: 'quart', options: { startsWith: true } },
  { text: 'final', options: { startsWith: true } },
  { text: 'semi', options: { startsWith: true } },
  { text: 'qual', options: { startsWith: true } },
  '1st rd',
  '1st round',
  '2nd round',
  '3rd round',
  '4th round',
  /*
  'final qualifing',
  'final qualifying',
  'final round',
  'final',
  'finalists',
  'finals',
  */
  'pqtr',
  'pre quarter finals',
  'pre quarters',
  'pre- quarters',
  'pre-quarter',
  'pre-quarters',
  'pre=qf',
  'preqtrs',
  'qf',
  'qtr final',
  'qtr',
  'qtrs',
  /*
  'qualifiers',
  'qualifyers',
  */
  'round 1',
  'round 2',
  'round 3',
  'round of 16',
  'round of 32',
  'round of 32',
  'round of 64',
  'round of 8',
  /*
  'semi final',
  'semi finals',
  'semi-final',
  'semi-finals',
  'semifinal',
  'semifinalists',
  'semifinals',
  */
  'sf',
  'winner',
  'winners'
];
