export const roundNames = [
  'round 1',
  'round 2',
  'round 3',
  'round of 64',
  'round of 32',
  'round of 16',
  'round of 8',
  '4th round',
  '1st round',
  '2nd round',
  '3rd round',
  'pre-quarter',
  'pre-quarters',
  'pre- quarters',
  'quarter- finals',
  'quarterfinalists',
  'preqtrs',
  'pqtr',
  'qtrs',
  'pre quarter finals',
  'quarters',
  'quarter',
  'qtr',
  'pre=qf',
  'qf',
  'qtr final',
  'qualifiers',
  'round of 32',
  'quarterfinals',
  'quarter final',
  'quarter finals',
  'final qualifying',
  'final qualifing',
  'semi final',
  'semifinal',
  'semifinals',
  'semifinalists',
  'semi finals',
  'semi-final',
  'semi-finals',
  'sf',
  'final round',
  'winners',
  'winner',
  'finalists',
  'finals',
  'final'
];
